on:
  push:
    branches:
      - main
      - release-v*
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        with:
          token: ${{ secrets.PRIVATE_TOKEN }}
          release-type: go
          default-branch: "${GITHUB_REF#refs/heads/}"